/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TherapiesRouteImport } from './routes/therapies'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TerapiasRouteImport } from './routes/terapias'
import { Route as SoyProfesionalRouteImport } from './routes/soy-profesional'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as ProfesionalesRouteImport } from './routes/profesionales'
import { Route as ProfesionalFundadorRouteImport } from './routes/profesional-fundador'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PlanPresenciaRouteImport } from './routes/plan-presencia'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForProfessionalsRouteImport } from './routes/for-professionals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ConfianzaRouteImport } from './routes/confianza'
import { Route as ComunidadFundadoraOrganizacionesRouteImport } from './routes/comunidad-fundadora-organizaciones'
import { Route as ComunidadFundadoraBienvenidaRouteImport } from './routes/comunidad-fundadora-bienvenida'
import { Route as ComunidadFundadoraAccesoRouteImport } from './routes/comunidad-fundadora-acceso'
import { Route as CodigoDeontologicoRouteImport } from './routes/codigo-deontologico'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TherapiesSlugRouteImport } from './routes/therapies_.$slug'
import { Route as TerapiasSlugRouteImport } from './routes/terapias_.$slug'
import { Route as ProfessionalsSlugRouteImport } from './routes/professionals_.$slug'
import { Route as ProfesionalesSlugRouteImport } from './routes/profesionales_.$slug'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ActivitiesNewRouteImport } from './routes/activities_.new'
import { Route as ActivitiesSlugRouteImport } from './routes/activities_.$slug'
import { Route as TherapiesSlugProfessionalsRouteImport } from './routes/therapies_.$slug.professionals'
import { Route as TerapiasSlugProfesionalesRouteImport } from './routes/terapias_.$slug.profesionales'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard/admin/analytics'
import { Route as ActivitiesSlugEditRouteImport } from './routes/activities_.$slug.edit'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapiesRoute = TherapiesRouteImport.update({
  id: '/therapies',
  path: '/therapies',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapiasRoute = TerapiasRouteImport.update({
  id: '/terapias',
  path: '/terapias',
  getParentRoute: () => rootRouteImport,
} as any)
const SoyProfesionalRoute = SoyProfesionalRouteImport.update({
  id: '/soy-profesional',
  path: '/soy-profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalesRoute = ProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalFundadorRoute = ProfesionalFundadorRouteImport.update({
  id: '/profesional-fundador',
  path: '/profesional-fundador',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPresenciaRoute = PlanPresenciaRouteImport.update({
  id: '/plan-presencia',
  path: '/plan-presencia',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProfessionalsRoute = ForProfessionalsRouteImport.update({
  id: '/for-professionals',
  path: '/for-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfianzaRoute = ConfianzaRouteImport.update({
  id: '/confianza',
  path: '/confianza',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadFundadoraOrganizacionesRoute =
  ComunidadFundadoraOrganizacionesRouteImport.update({
    id: '/comunidad-fundadora-organizaciones',
    path: '/comunidad-fundadora-organizaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadFundadoraBienvenidaRoute =
  ComunidadFundadoraBienvenidaRouteImport.update({
    id: '/comunidad-fundadora-bienvenida',
    path: '/comunidad-fundadora-bienvenida',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadFundadoraAccesoRoute =
  ComunidadFundadoraAccesoRouteImport.update({
    id: '/comunidad-fundadora-acceso',
    path: '/comunidad-fundadora-acceso',
    getParentRoute: () => rootRouteImport,
  } as any)
const CodigoDeontologicoRoute = CodigoDeontologicoRouteImport.update({
  id: '/codigo-deontologico',
  path: '/codigo-deontologico',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TherapiesSlugRoute = TherapiesSlugRouteImport.update({
  id: '/therapies_/$slug',
  path: '/therapies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapiasSlugRoute = TerapiasSlugRouteImport.update({
  id: '/terapias_/$slug',
  path: '/terapias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsSlugRoute = ProfessionalsSlugRouteImport.update({
  id: '/professionals_/$slug',
  path: '/professionals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalesSlugRoute = ProfesionalesSlugRouteImport.update({
  id: '/profesionales_/$slug',
  path: '/profesionales/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/activities_/new',
  path: '/activities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities_/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapiesSlugProfessionalsRoute =
  TherapiesSlugProfessionalsRouteImport.update({
    id: '/professionals',
    path: '/professionals',
    getParentRoute: () => TherapiesSlugRoute,
  } as any)
const TerapiasSlugProfesionalesRoute =
  TerapiasSlugProfesionalesRouteImport.update({
    id: '/profesionales',
    path: '/profesionales',
    getParentRoute: () => TerapiasSlugRoute,
  } as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ActivitiesSlugEditRoute = ActivitiesSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ActivitiesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/activities': typeof ActivitiesRoute
  '/buscar': typeof BuscarRoute
  '/codigo-deontologico': typeof CodigoDeontologicoRoute
  '/comunidad-fundadora-acceso': typeof ComunidadFundadoraAccesoRoute
  '/comunidad-fundadora-bienvenida': typeof ComunidadFundadoraBienvenidaRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/confianza': typeof ConfianzaRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-professionals': typeof ForProfessionalsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-presencia': typeof PlanPresenciaRoute
  '/planes': typeof PlanesRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/profesionales': typeof ProfesionalesRoute
  '/professionals': typeof ProfessionalsRoute
  '/register': typeof RegisterRoute
  '/registro': typeof RegistroRoute
  '/search': typeof SearchRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/terapias': typeof TerapiasRoute
  '/terms': typeof TermsRoute
  '/therapies': typeof TherapiesRoute
  '/trust': typeof TrustRoute
  '/activities/$slug': typeof ActivitiesSlugRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/profesionales/$slug': typeof ProfesionalesSlugRoute
  '/professionals/$slug': typeof ProfessionalsSlugRoute
  '/terapias/$slug': typeof TerapiasSlugRouteWithChildren
  '/therapies/$slug': typeof TherapiesSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/activities/$slug/edit': typeof ActivitiesSlugEditRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/terapias/$slug/profesionales': typeof TerapiasSlugProfesionalesRoute
  '/therapies/$slug/professionals': typeof TherapiesSlugProfessionalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/activities': typeof ActivitiesRoute
  '/buscar': typeof BuscarRoute
  '/codigo-deontologico': typeof CodigoDeontologicoRoute
  '/comunidad-fundadora-acceso': typeof ComunidadFundadoraAccesoRoute
  '/comunidad-fundadora-bienvenida': typeof ComunidadFundadoraBienvenidaRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/confianza': typeof ConfianzaRoute
  '/cookies': typeof CookiesRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-presencia': typeof PlanPresenciaRoute
  '/planes': typeof PlanesRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/profesionales': typeof ProfesionalesRoute
  '/professionals': typeof ProfessionalsRoute
  '/register': typeof RegisterRoute
  '/registro': typeof RegistroRoute
  '/search': typeof SearchRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/terapias': typeof TerapiasRoute
  '/terms': typeof TermsRoute
  '/therapies': typeof TherapiesRoute
  '/trust': typeof TrustRoute
  '/activities/$slug': typeof ActivitiesSlugRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/profesionales/$slug': typeof ProfesionalesSlugRoute
  '/professionals/$slug': typeof ProfessionalsSlugRoute
  '/terapias/$slug': typeof TerapiasSlugRouteWithChildren
  '/therapies/$slug': typeof TherapiesSlugRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/activities/$slug/edit': typeof ActivitiesSlugEditRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/terapias/$slug/profesionales': typeof TerapiasSlugProfesionalesRoute
  '/therapies/$slug/professionals': typeof TherapiesSlugProfessionalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/activities': typeof ActivitiesRoute
  '/buscar': typeof BuscarRoute
  '/codigo-deontologico': typeof CodigoDeontologicoRoute
  '/comunidad-fundadora-acceso': typeof ComunidadFundadoraAccesoRoute
  '/comunidad-fundadora-bienvenida': typeof ComunidadFundadoraBienvenidaRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/confianza': typeof ConfianzaRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/for-professionals': typeof ForProfessionalsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan-presencia': typeof PlanPresenciaRoute
  '/planes': typeof PlanesRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/profesionales': typeof ProfesionalesRoute
  '/professionals': typeof ProfessionalsRoute
  '/register': typeof RegisterRoute
  '/registro': typeof RegistroRoute
  '/search': typeof SearchRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/terapias': typeof TerapiasRoute
  '/terms': typeof TermsRoute
  '/therapies': typeof TherapiesRoute
  '/trust': typeof TrustRoute
  '/activities_/$slug': typeof ActivitiesSlugRouteWithChildren
  '/activities_/new': typeof ActivitiesNewRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/profesionales_/$slug': typeof ProfesionalesSlugRoute
  '/professionals_/$slug': typeof ProfessionalsSlugRoute
  '/terapias_/$slug': typeof TerapiasSlugRouteWithChildren
  '/therapies_/$slug': typeof TherapiesSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/activities_/$slug/edit': typeof ActivitiesSlugEditRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/terapias_/$slug/profesionales': typeof TerapiasSlugProfesionalesRoute
  '/therapies_/$slug/professionals': typeof TherapiesSlugProfessionalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/activities'
    | '/buscar'
    | '/codigo-deontologico'
    | '/comunidad-fundadora-acceso'
    | '/comunidad-fundadora-bienvenida'
    | '/comunidad-fundadora-organizaciones'
    | '/confianza'
    | '/cookies'
    | '/dashboard'
    | '/for-professionals'
    | '/login'
    | '/onboarding'
    | '/plan-presencia'
    | '/planes'
    | '/plans'
    | '/privacy'
    | '/profesional-fundador'
    | '/profesionales'
    | '/professionals'
    | '/register'
    | '/registro'
    | '/search'
    | '/soy-profesional'
    | '/terapias'
    | '/terms'
    | '/therapies'
    | '/trust'
    | '/activities/$slug'
    | '/activities/new'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/profesionales/$slug'
    | '/professionals/$slug'
    | '/terapias/$slug'
    | '/therapies/$slug'
    | '/dashboard/'
    | '/activities/$slug/edit'
    | '/dashboard/admin/analytics'
    | '/terapias/$slug/profesionales'
    | '/therapies/$slug/professionals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/activities'
    | '/buscar'
    | '/codigo-deontologico'
    | '/comunidad-fundadora-acceso'
    | '/comunidad-fundadora-bienvenida'
    | '/comunidad-fundadora-organizaciones'
    | '/confianza'
    | '/cookies'
    | '/for-professionals'
    | '/login'
    | '/onboarding'
    | '/plan-presencia'
    | '/planes'
    | '/plans'
    | '/privacy'
    | '/profesional-fundador'
    | '/profesionales'
    | '/professionals'
    | '/register'
    | '/registro'
    | '/search'
    | '/soy-profesional'
    | '/terapias'
    | '/terms'
    | '/therapies'
    | '/trust'
    | '/activities/$slug'
    | '/activities/new'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/profesionales/$slug'
    | '/professionals/$slug'
    | '/terapias/$slug'
    | '/therapies/$slug'
    | '/dashboard'
    | '/activities/$slug/edit'
    | '/dashboard/admin/analytics'
    | '/terapias/$slug/profesionales'
    | '/therapies/$slug/professionals'
  id:
    | '__root__'
    | '/'
    | '/actividades'
    | '/activities'
    | '/buscar'
    | '/codigo-deontologico'
    | '/comunidad-fundadora-acceso'
    | '/comunidad-fundadora-bienvenida'
    | '/comunidad-fundadora-organizaciones'
    | '/confianza'
    | '/cookies'
    | '/dashboard'
    | '/for-professionals'
    | '/login'
    | '/onboarding'
    | '/plan-presencia'
    | '/planes'
    | '/plans'
    | '/privacy'
    | '/profesional-fundador'
    | '/profesionales'
    | '/professionals'
    | '/register'
    | '/registro'
    | '/search'
    | '/soy-profesional'
    | '/terapias'
    | '/terms'
    | '/therapies'
    | '/trust'
    | '/activities_/$slug'
    | '/activities_/new'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/profesionales_/$slug'
    | '/professionals_/$slug'
    | '/terapias_/$slug'
    | '/therapies_/$slug'
    | '/dashboard/'
    | '/activities_/$slug/edit'
    | '/dashboard/admin/analytics'
    | '/terapias_/$slug/profesionales'
    | '/therapies_/$slug/professionals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesRoute: typeof ActividadesRoute
  ActivitiesRoute: typeof ActivitiesRoute
  BuscarRoute: typeof BuscarRoute
  CodigoDeontologicoRoute: typeof CodigoDeontologicoRoute
  ComunidadFundadoraAccesoRoute: typeof ComunidadFundadoraAccesoRoute
  ComunidadFundadoraBienvenidaRoute: typeof ComunidadFundadoraBienvenidaRoute
  ComunidadFundadoraOrganizacionesRoute: typeof ComunidadFundadoraOrganizacionesRoute
  ConfianzaRoute: typeof ConfianzaRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForProfessionalsRoute: typeof ForProfessionalsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanPresenciaRoute: typeof PlanPresenciaRoute
  PlanesRoute: typeof PlanesRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfesionalFundadorRoute: typeof ProfesionalFundadorRoute
  ProfesionalesRoute: typeof ProfesionalesRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  RegisterRoute: typeof RegisterRoute
  RegistroRoute: typeof RegistroRoute
  SearchRoute: typeof SearchRoute
  SoyProfesionalRoute: typeof SoyProfesionalRoute
  TerapiasRoute: typeof TerapiasRoute
  TermsRoute: typeof TermsRoute
  TherapiesRoute: typeof TherapiesRoute
  TrustRoute: typeof TrustRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRouteWithChildren
  ActivitiesNewRoute: typeof ActivitiesNewRoute
  ProfesionalesSlugRoute: typeof ProfesionalesSlugRoute
  ProfessionalsSlugRoute: typeof ProfessionalsSlugRoute
  TerapiasSlugRoute: typeof TerapiasSlugRouteWithChildren
  TherapiesSlugRoute: typeof TherapiesSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapies': {
      id: '/therapies'
      path: '/therapies'
      fullPath: '/therapies'
      preLoaderRoute: typeof TherapiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapias': {
      id: '/terapias'
      path: '/terapias'
      fullPath: '/terapias'
      preLoaderRoute: typeof TerapiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soy-profesional': {
      id: '/soy-profesional'
      path: '/soy-profesional'
      fullPath: '/soy-profesional'
      preLoaderRoute: typeof SoyProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesionales': {
      id: '/profesionales'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof ProfesionalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional-fundador': {
      id: '/profesional-fundador'
      path: '/profesional-fundador'
      fullPath: '/profesional-fundador'
      preLoaderRoute: typeof ProfesionalFundadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-presencia': {
      id: '/plan-presencia'
      path: '/plan-presencia'
      fullPath: '/plan-presencia'
      preLoaderRoute: typeof PlanPresenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-professionals': {
      id: '/for-professionals'
      path: '/for-professionals'
      fullPath: '/for-professionals'
      preLoaderRoute: typeof ForProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confianza': {
      id: '/confianza'
      path: '/confianza'
      fullPath: '/confianza'
      preLoaderRoute: typeof ConfianzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-organizaciones': {
      id: '/comunidad-fundadora-organizaciones'
      path: '/comunidad-fundadora-organizaciones'
      fullPath: '/comunidad-fundadora-organizaciones'
      preLoaderRoute: typeof ComunidadFundadoraOrganizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-bienvenida': {
      id: '/comunidad-fundadora-bienvenida'
      path: '/comunidad-fundadora-bienvenida'
      fullPath: '/comunidad-fundadora-bienvenida'
      preLoaderRoute: typeof ComunidadFundadoraBienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-acceso': {
      id: '/comunidad-fundadora-acceso'
      path: '/comunidad-fundadora-acceso'
      fullPath: '/comunidad-fundadora-acceso'
      preLoaderRoute: typeof ComunidadFundadoraAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo-deontologico': {
      id: '/codigo-deontologico'
      path: '/codigo-deontologico'
      fullPath: '/codigo-deontologico'
      preLoaderRoute: typeof CodigoDeontologicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/therapies_/$slug': {
      id: '/therapies_/$slug'
      path: '/therapies/$slug'
      fullPath: '/therapies/$slug'
      preLoaderRoute: typeof TherapiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapias_/$slug': {
      id: '/terapias_/$slug'
      path: '/terapias/$slug'
      fullPath: '/terapias/$slug'
      preLoaderRoute: typeof TerapiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals_/$slug': {
      id: '/professionals_/$slug'
      path: '/professionals/$slug'
      fullPath: '/professionals/$slug'
      preLoaderRoute: typeof ProfessionalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesionales_/$slug': {
      id: '/profesionales_/$slug'
      path: '/profesionales/$slug'
      fullPath: '/profesionales/$slug'
      preLoaderRoute: typeof ProfesionalesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/activities_/new': {
      id: '/activities_/new'
      path: '/activities/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities_/$slug': {
      id: '/activities_/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapies_/$slug/professionals': {
      id: '/therapies_/$slug/professionals'
      path: '/professionals'
      fullPath: '/therapies/$slug/professionals'
      preLoaderRoute: typeof TherapiesSlugProfessionalsRouteImport
      parentRoute: typeof TherapiesSlugRoute
    }
    '/terapias_/$slug/profesionales': {
      id: '/terapias_/$slug/profesionales'
      path: '/profesionales'
      fullPath: '/terapias/$slug/profesionales'
      preLoaderRoute: typeof TerapiasSlugProfesionalesRouteImport
      parentRoute: typeof TerapiasSlugRoute
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/activities_/$slug/edit': {
      id: '/activities_/$slug/edit'
      path: '/edit'
      fullPath: '/activities/$slug/edit'
      preLoaderRoute: typeof ActivitiesSlugEditRouteImport
      parentRoute: typeof ActivitiesSlugRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ActivitiesSlugRouteChildren {
  ActivitiesSlugEditRoute: typeof ActivitiesSlugEditRoute
}

const ActivitiesSlugRouteChildren: ActivitiesSlugRouteChildren = {
  ActivitiesSlugEditRoute: ActivitiesSlugEditRoute,
}

const ActivitiesSlugRouteWithChildren = ActivitiesSlugRoute._addFileChildren(
  ActivitiesSlugRouteChildren,
)

interface TerapiasSlugRouteChildren {
  TerapiasSlugProfesionalesRoute: typeof TerapiasSlugProfesionalesRoute
}

const TerapiasSlugRouteChildren: TerapiasSlugRouteChildren = {
  TerapiasSlugProfesionalesRoute: TerapiasSlugProfesionalesRoute,
}

const TerapiasSlugRouteWithChildren = TerapiasSlugRoute._addFileChildren(
  TerapiasSlugRouteChildren,
)

interface TherapiesSlugRouteChildren {
  TherapiesSlugProfessionalsRoute: typeof TherapiesSlugProfessionalsRoute
}

const TherapiesSlugRouteChildren: TherapiesSlugRouteChildren = {
  TherapiesSlugProfessionalsRoute: TherapiesSlugProfessionalsRoute,
}

const TherapiesSlugRouteWithChildren = TherapiesSlugRoute._addFileChildren(
  TherapiesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesRoute: ActividadesRoute,
  ActivitiesRoute: ActivitiesRoute,
  BuscarRoute: BuscarRoute,
  CodigoDeontologicoRoute: CodigoDeontologicoRoute,
  ComunidadFundadoraAccesoRoute: ComunidadFundadoraAccesoRoute,
  ComunidadFundadoraBienvenidaRoute: ComunidadFundadoraBienvenidaRoute,
  ComunidadFundadoraOrganizacionesRoute: ComunidadFundadoraOrganizacionesRoute,
  ConfianzaRoute: ConfianzaRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForProfessionalsRoute: ForProfessionalsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlanPresenciaRoute: PlanPresenciaRoute,
  PlanesRoute: PlanesRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfesionalFundadorRoute: ProfesionalFundadorRoute,
  ProfesionalesRoute: ProfesionalesRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  RegisterRoute: RegisterRoute,
  RegistroRoute: RegistroRoute,
  SearchRoute: SearchRoute,
  SoyProfesionalRoute: SoyProfesionalRoute,
  TerapiasRoute: TerapiasRoute,
  TermsRoute: TermsRoute,
  TherapiesRoute: TherapiesRoute,
  TrustRoute: TrustRoute,
  ActivitiesSlugRoute: ActivitiesSlugRouteWithChildren,
  ActivitiesNewRoute: ActivitiesNewRoute,
  ProfesionalesSlugRoute: ProfesionalesSlugRoute,
  ProfessionalsSlugRoute: ProfessionalsSlugRoute,
  TerapiasSlugRoute: TerapiasSlugRouteWithChildren,
  TherapiesSlugRoute: TherapiesSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
