INSERT INTO public.help_areas (slug, name, description, keywords)
VALUES
  ('adicciones', 'Adicciones', 'Acompañamiento en procesos relacionados con dependencias y hábitos compulsivos.', ARRAY['adicciones','dependencias','habitos compulsivos']),
  ('alimentacion', 'Alimentación', 'Apoyo en relación con alimentación, hábitos nutricionales y bienestar digestivo.', ARRAY['alimentacion','nutricion','habitos']),
  ('alergias', 'Alergias', 'Acompañamiento complementario para personas con alergias o sensibilidad ambiental.', ARRAY['alergias','sensibilidad','inmunidad']),
  ('ansiedad', 'Ansiedad', 'Acompañamiento para ansiedad, nerviosismo y sensación de alerta.', ARRAY['ansiedad','nervios','preocupacion']),
  ('autoestima-y-confianza', 'Autoestima y confianza', 'Procesos para fortalecer autoestima, seguridad y confianza personal.', ARRAY['autoestima','confianza','seguridad']),
  ('bienestar-animal', 'Bienestar animal', 'Acompañamiento y bienestar aplicado a animales.', ARRAY['animales','bienestar animal','mascotas']),
  ('bienestar-general', 'Bienestar general', 'Apoyo para equilibrio, prevención y mejora del bienestar cotidiano.', ARRAY['bienestar','equilibrio','salud']),
  ('burnout', 'Burnout', 'Acompañamiento para agotamiento profesional y sobrecarga sostenida.', ARRAY['burnout','agotamiento','sobrecarga']),
  ('cansancio-y-fatiga', 'Cansancio y fatiga', 'Apoyo para cansancio, fatiga y baja energía.', ARRAY['cansancio','fatiga','energia']),
  ('crecimiento-personal', 'Crecimiento personal', 'Procesos de autoconocimiento, cambio y desarrollo personal.', ARRAY['crecimiento','autoconocimiento','cambio']),
  ('depresion-y-estado-de-animo-bajo', 'Depresión y estado de ánimo bajo', 'Acompañamiento complementario en tristeza, apatía y ánimo bajo.', ARRAY['depresion','tristeza','animo bajo']),
  ('dolor-abdominal', 'Dolor abdominal', 'Acompañamiento en molestias abdominales y tensión digestiva.', ARRAY['dolor abdominal','abdomen','digestivo']),
  ('dolor-de-cabeza', 'Dolor de cabeza', 'Apoyo para cefaleas, migrañas y tensión en cabeza.', ARRAY['dolor de cabeza','cefalea','migraña']),
  ('dolor-de-espalda', 'Dolor de espalda', 'Acompañamiento para dolor lumbar, dorsal o cervical.', ARRAY['espalda','dolor lumbar','cervical']),
  ('dolores-articulares', 'Dolores articulares', 'Apoyo para molestias articulares y movilidad.', ARRAY['articulaciones','dolor articular','movilidad']),
  ('dolores-cronicos', 'Dolores crónicos', 'Acompañamiento para dolores persistentes o recurrentes.', ARRAY['dolor cronico','dolores cronicos','persistente']),
  ('dolores-musculares', 'Dolores musculares', 'Apoyo para tensión, contracturas y dolor muscular.', ARRAY['muscular','contracturas','tension']),
  ('embarazo-y-maternidad', 'Embarazo y maternidad', 'Acompañamiento durante embarazo, posparto y maternidad.', ARRAY['embarazo','maternidad','posparto']),
  ('estres', 'Estrés', 'Acompañamiento para estrés, tensión y sobrecarga.', ARRAY['estres','tension','sobrecarga']),
  ('fertilidad', 'Fertilidad', 'Apoyo complementario en procesos de fertilidad.', ARRAY['fertilidad','concepcion','ciclo']),
  ('fobias-y-miedos', 'Fobias y miedos', 'Acompañamiento para miedos, fobias y bloqueos.', ARRAY['fobias','miedos','bloqueos']),
  ('gestion-emocional', 'Gestión emocional', 'Herramientas para reconocer, expresar y regular emociones.', ARRAY['emociones','gestion emocional','regulacion']),
  ('hogar-y-espacios', 'Hogar y espacios', 'Bienestar aplicado al hogar, espacios y entornos.', ARRAY['hogar','espacios','entorno']),
  ('habitos-y-estilo-de-vida', 'Hábitos y estilo de vida', 'Apoyo para hábitos saludables y cambios sostenibles.', ARRAY['habitos','estilo de vida','rutinas']),
  ('inmunidad', 'Inmunidad', 'Acompañamiento complementario para vitalidad e inmunidad.', ARRAY['inmunidad','defensas','vitalidad']),
  ('insomnio-y-problemas-de-sueno', 'Insomnio y problemas de sueño', 'Apoyo para insomnio, descanso y calidad del sueño.', ARRAY['insomnio','sueño','descanso']),
  ('intolerancias-alimentarias', 'Intolerancias alimentarias', 'Acompañamiento en sensibilidad e intolerancias alimentarias.', ARRAY['intolerancias','alimentarias','digestivo']),
  ('perdida-de-peso', 'Pérdida de peso', 'Apoyo para cambio de hábitos y relación con el peso.', ARRAY['peso','perdida de peso','habitos']),
  ('piel-y-afecciones-cutaneas', 'Piel y afecciones cutáneas', 'Acompañamiento complementario en bienestar de la piel.', ARRAY['piel','cutaneo','afecciones']),
  ('preparacion-mental', 'Preparación mental', 'Apoyo para foco, claridad y preparación emocional o mental.', ARRAY['preparacion mental','foco','claridad']),
  ('problemas-cardiovasculares', 'Problemas cardiovasculares', 'Acompañamiento complementario en bienestar cardiovascular.', ARRAY['cardiovascular','corazon','circulacion']),
  ('problemas-de-audicion', 'Problemas de audición', 'Acompañamiento complementario relacionado con audición.', ARRAY['audicion','oido','escucha']),
  ('problemas-de-comportamiento', 'Problemas de comportamiento', 'Apoyo para conducta, hábitos y patrones de comportamiento.', ARRAY['comportamiento','conducta','patrones']),
  ('problemas-de-circulacion', 'Problemas de circulación', 'Acompañamiento complementario para circulación y piernas cansadas.', ARRAY['circulacion','piernas cansadas','vascular']),
  ('problemas-de-pareja-y-relaciones', 'Problemas de pareja y relaciones', 'Acompañamiento en vínculos, pareja y relaciones.', ARRAY['pareja','relaciones','vinculos']),
  ('problemas-de-vision', 'Problemas de visión', 'Acompañamiento complementario relacionado con visión.', ARRAY['vision','ojos','vista']),
  ('problemas-digestivos', 'Problemas digestivos', 'Apoyo en digestión, molestias digestivas y hábitos alimentarios.', ARRAY['digestivo','digestion','estomago']),
  ('problemas-urinarios', 'Problemas urinarios', 'Acompañamiento complementario en bienestar urinario.', ARRAY['urinario','vejiga','riñon']),
  ('salud-bucodental', 'Salud bucodental', 'Acompañamiento complementario para bienestar bucodental.', ARRAY['bucodental','boca','dental']),
  ('salud-femenina', 'Salud femenina', 'Acompañamiento en ciclo, etapas vitales y bienestar femenino.', ARRAY['salud femenina','ciclo','hormonal']),
  ('salud-sexual', 'Salud sexual', 'Acompañamiento en bienestar sexual y relación con el cuerpo.', ARRAY['salud sexual','sexualidad','cuerpo']),
  ('sistema-respiratorio-orl', 'Sistema respiratorio (ORL)', 'Acompañamiento complementario para respiración y zona ORL.', ARRAY['respiratorio','orl','respiracion']),
  ('traumas-y-experiencias-dificiles', 'Traumas y experiencias difíciles', 'Acompañamiento sensible para experiencias difíciles y trauma.', ARRAY['trauma','experiencias dificiles','bloqueo']),
  ('rendimiento-deportivo', 'Rendimiento deportivo', 'Apoyo para recuperación, foco y rendimiento deportivo.', ARRAY['deporte','rendimiento','recuperacion']),
  ('otro', 'Otro (indica cuál)', 'Área abierta para especializaciones no incluidas en la lista.', ARRAY['otro','otra area','especializacion'])
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  keywords = EXCLUDED.keywords;
